### ISSUE TITLE
指数阈值和FPN

### ISSUE THREAD

**Issue by Randomless** [DotWang/DFC2020#1]
你好,想请教一下以下的问题:
1. 根据指数(NDVI NDWI等) 设置阈值,对label的类别进行矫正,阈值设置的出处是哪里?还是目视估计?
2. DeeplabFPN在dfc2020数据集或其他数据集上测试 是否相对于Deeplab  精度有提升?

**Comment by DotWang** [comment]
1.DFC2020数据集非常复杂，光植被就分好几种，很难自适应得到阈值，所以是目视获得的
2.DeeplabFPN在其他数据集上精度要高于Deeplab，但是DFC2020数据集的标签误差很大，网络学习能力越强，精度反而越低，所以这个比赛的关键在于标签提纯，遗憾的是我们最后还是没有很好地获得较为纯净的标签

**Comment by DotWang** [comment]
> 你好,想请教一下以下的问题:
> 
> 1. 根据指数(NDVI NDWI等) 设置阈值,对label的类别进行矫正,阈值设置的出处是哪里?还是目视估计?
> 2. DeeplabFPN在dfc2020数据集或其他数据集上测试 是否相对于Deeplab  精度有提升?

1.DFC2020数据集非常复杂，光植被就分好几种，很难自适应得到阈值，所以是目视获得的
2.DeeplabFPN在其他数据集上精度要高于Deeplab，但是DFC2020数据集的标签误差很大，网络学习能力越强，精度反而越低，所以这个比赛的关键在于标签提纯，遗憾的是我们最后还是没有很好地获得较为纯净的标签

**Comment by Randomless** [comment]
多谢解答
